#
# Changes to this file will be overwritten by `trmnlp pull`.
#
# Docs: https://help.usetrmnl.com/en/articles/10542599-importing-and-exporting-private-plugins#h_581fb988f0
#
---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: 'https://api.tmb.cat/v1/alerts/metro/channels/WEB'
polling_headers: 'app_id={{ userAppId }}&app_key={{ userAppKey }}'
polling_body: ''
icon: media/icon.svg
name: TMB Outages
refresh_interval: 30
custom_fields:
- keyname: userAppId
  field_type: string
  name: App ID
  description: Your app_id from the TMB developer portal.
  help_text: Register for free at the <a href="https://developer.tmb.cat/docs/getting-started">developer site</a>.
- keyname: userAppKey
  field_type: string
  name: App Key
  description: Your app_key from the TMB developer portal.
  help_text: Retrieve your app_id and app_key from the dashboard after signing up.
- keyname: author_bio
  field_type: author_bio
  name: About This Plugin
  description: "Created by Ivan Perez. This plugin is for monitoring real-time metro outages in Barcelona on your TRMNL device."
  category: "news,travel"
  github_url: "https://github.com/taichikuji/trmnl-tmb-plugin"
